"""fase_4b_bloco3_biblioteca_inteligente

Revision ID: 219b00575db0
Revises: e4bd625e5e7d
Create Date: 2026-07-19 13:40:47.506181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219b00575db0'
down_revision: Union[str, None] = 'e4bd625e5e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_links',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=True),
    sa.Column('objective_id', sa.Uuid(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(training_id IS NOT NULL AND objective_id IS NULL) OR (training_id IS NULL AND objective_id IS NOT NULL)', name='ck_resource_links_single_target'),
    sa.CheckConstraint('relevance_score BETWEEN 1 AND 5', name='ck_resource_links_relevance_score_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_links_id'), 'resource_links', ['id'], unique=False)
    op.create_index(op.f('ix_resource_links_objective_id'), 'resource_links', ['objective_id'], unique=False)
    op.create_index(op.f('ix_resource_links_resource_id'), 'resource_links', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_links_training_id'), 'resource_links', ['training_id'], unique=False)
    op.create_index('uq_resource_links_resource_objective', 'resource_links', ['resource_id', 'objective_id'], unique=True, postgresql_where=sa.text('objective_id IS NOT NULL'))
    op.create_index('uq_resource_links_resource_training', 'resource_links', ['resource_id', 'training_id'], unique=True, postgresql_where=sa.text('training_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_resource_links_resource_training', table_name='resource_links', postgresql_where=sa.text('training_id IS NOT NULL'))
    op.drop_index('uq_resource_links_resource_objective', table_name='resource_links', postgresql_where=sa.text('objective_id IS NOT NULL'))
    op.drop_index(op.f('ix_resource_links_training_id'), table_name='resource_links')
    op.drop_index(op.f('ix_resource_links_resource_id'), table_name='resource_links')
    op.drop_index(op.f('ix_resource_links_objective_id'), table_name='resource_links')
    op.drop_index(op.f('ix_resource_links_id'), table_name='resource_links')
    op.drop_table('resource_links')
    # ### end Alembic commands ###
