"""fase5_bloco2_white_label

Revision ID: 3cfd4510cd4e
Revises: 988fb711e782
Create Date: 2026-07-19 19:18:26.494780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfd4510cd4e'
down_revision: Union[str, None] = '988fb711e782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('white_label_logo_url', sa.String(length=1024), nullable=True))
    op.add_column('clinics', sa.Column('white_label_brand_color', sa.String(length=7), nullable=True))
    op.add_column('clinics', sa.Column('white_label_display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'white_label_display_name')
    op.drop_column('clinics', 'white_label_brand_color')
    op.drop_column('clinics', 'white_label_logo_url')
    # ### end Alembic commands ###
