"""fase7_modulo32_anamnesis_checklists

Revision ID: 5b51e9e11096
Revises: 8c82289a2fc6
Create Date: 2026-07-22 01:50:20.959762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b51e9e11096'
down_revision: Union[str, None] = '8c82289a2fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_checklist_templates',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_checklist_templates_clinic_id'), 'custom_checklist_templates', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_custom_checklist_templates_id'), 'custom_checklist_templates', ['id'], unique=False)
    op.create_index(op.f('ix_custom_checklist_templates_individual_owner_id'), 'custom_checklist_templates', ['individual_owner_id'], unique=False)
    op.create_table('anamneses',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('birth_history', sa.Text(), nullable=True),
    sa.Column('developmental_history', sa.Text(), nullable=True),
    sa.Column('developmental_milestones', sa.Text(), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_anamneses_patient_id')
    )
    op.create_index(op.f('ix_anamneses_clinic_id'), 'anamneses', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_anamneses_id'), 'anamneses', ['id'], unique=False)
    op.create_index(op.f('ix_anamneses_individual_owner_id'), 'anamneses', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_anamneses_patient_id'), 'anamneses', ['patient_id'], unique=False)
    op.create_table('checklist_responses',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('applied_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['custom_checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_responses_clinic_id'), 'checklist_responses', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_checklist_responses_id'), 'checklist_responses', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_responses_individual_owner_id'), 'checklist_responses', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_checklist_responses_patient_id'), 'checklist_responses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_checklist_responses_template_id'), 'checklist_responses', ['template_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id /
    # fk_users_clinic_id (both use_alter=True FKs) and dropping
    # ix_objectives_title_trgm / ix_sessions_patient_id_occurred_at — this is
    # pre-existing drift unrelated to this migration (see backend/README.md),
    # stripped here as in every prior migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_responses_template_id'), table_name='checklist_responses')
    op.drop_index(op.f('ix_checklist_responses_patient_id'), table_name='checklist_responses')
    op.drop_index(op.f('ix_checklist_responses_individual_owner_id'), table_name='checklist_responses')
    op.drop_index(op.f('ix_checklist_responses_id'), table_name='checklist_responses')
    op.drop_index(op.f('ix_checklist_responses_clinic_id'), table_name='checklist_responses')
    op.drop_table('checklist_responses')
    op.drop_index(op.f('ix_anamneses_patient_id'), table_name='anamneses')
    op.drop_index(op.f('ix_anamneses_individual_owner_id'), table_name='anamneses')
    op.drop_index(op.f('ix_anamneses_id'), table_name='anamneses')
    op.drop_index(op.f('ix_anamneses_clinic_id'), table_name='anamneses')
    op.drop_table('anamneses')
    op.drop_index(op.f('ix_custom_checklist_templates_individual_owner_id'), table_name='custom_checklist_templates')
    op.drop_index(op.f('ix_custom_checklist_templates_id'), table_name='custom_checklist_templates')
    op.drop_index(op.f('ix_custom_checklist_templates_clinic_id'), table_name='custom_checklist_templates')
    op.drop_table('custom_checklist_templates')
    # ### end Alembic commands ###
