"""fase 3 rbac settings and invitation role

Revision ID: 6ee3158ccc10
Revises: fb41781cb679
Create Date: 2026-07-18 13:21:35.144066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee3158ccc10'
down_revision: Union[str, None] = 'fb41781cb679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_permission_settings',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('professionals_can_create_patients', sa.Boolean(), nullable=False),
    sa.Column('supervisors_can_register_sessions', sa.Boolean(), nullable=False),
    sa.Column('supervisors_can_edit_any_objective_area', sa.Boolean(), nullable=False),
    sa.Column('admins_can_edit_any_objective_area', sa.Boolean(), nullable=False),
    sa.Column('supervisors_can_restore_deleted_data', sa.Boolean(), nullable=False),
    sa.Column('supervisors_can_generate_invitations', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', name='uq_clinic_permission_settings_clinic_id')
    )
    op.create_index(op.f('ix_clinic_permission_settings_clinic_id'), 'clinic_permission_settings', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_permission_settings_id'), 'clinic_permission_settings', ['id'], unique=False)
    op.add_column(
        'invitations',
        sa.Column(
            'role',
            sa.Enum('CLINIC_ADMIN', 'PROFESSIONAL', 'INDIVIDUAL', 'SUPERVISOR', name='usertype'),
            nullable=False,
            server_default='PROFESSIONAL',
        ),
    )
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping the
    # manually-added ix_objectives_title_trgm/ix_sessions_patient_id_occurred_at indexes (not
    # represented in the ORM model). All were removed from this migration on review.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'role')
    op.drop_index(op.f('ix_clinic_permission_settings_id'), table_name='clinic_permission_settings')
    op.drop_index(op.f('ix_clinic_permission_settings_clinic_id'), table_name='clinic_permission_settings')
    op.drop_table('clinic_permission_settings')
    # ### end Alembic commands ###
