"""fase7_modulo31_behavior_events_reinforcers_session_media

Revision ID: 8c82289a2fc6
Revises: f42cc4c0c8bd
Create Date: 2026-07-22 01:24:48.678083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8c82289a2fc6'
down_revision: Union[str, None] = 'f42cc4c0c8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reinforcers',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effectiveness_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reinforcers_clinic_id'), 'reinforcers', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_reinforcers_id'), 'reinforcers', ['id'], unique=False)
    op.create_index(op.f('ix_reinforcers_individual_owner_id'), 'reinforcers', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_reinforcers_patient_id'), 'reinforcers', ['patient_id'], unique=False)
    op.create_table('behavior_events',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('antecedent', sa.Text(), nullable=False),
    sa.Column('behavior', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='behaviorintensity'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_events_clinic_id'), 'behavior_events', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_behavior_events_id'), 'behavior_events', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_events_individual_owner_id'), 'behavior_events', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_behavior_events_patient_id'), 'behavior_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_behavior_events_session_id'), 'behavior_events', ['session_id'], unique=False)
    op.create_table('session_reinforcers',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('reinforcer_id', sa.Uuid(), nullable=False),
    sa.Column('effectiveness_note', sa.Text(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reinforcer_id'], ['reinforcers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_reinforcers_id'), 'session_reinforcers', ['id'], unique=False)
    op.create_index(op.f('ix_session_reinforcers_reinforcer_id'), 'session_reinforcers', ['reinforcer_id'], unique=False)
    op.create_index(op.f('ix_session_reinforcers_session_id'), 'session_reinforcers', ['session_id'], unique=False)
    # NOTE (Fase 6 bloco 7 postmortem, ver backend/README.md): op.add_column
    # numa tabela já existente não emite CREATE TYPE sozinho para um enum novo
    # — diferente de create_table, que cuida disso implicitamente. Criamos o
    # tipo explicitamente e usamos create_type=False no add_column.
    session_media_type_enum = postgresql.ENUM('PHOTO', 'VIDEO', name='sessionmediatype')
    session_media_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('sessions', sa.Column('media_key', sa.String(length=500), nullable=True))
    op.add_column(
        'sessions',
        sa.Column('media_type', postgresql.ENUM('PHOTO', 'VIDEO', name='sessionmediatype', create_type=False), nullable=True),
    )
    op.add_column('sessions', sa.Column('media_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('media_uploaded_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_sessions_media_uploaded_by_user_id', 'sessions', 'users', ['media_uploaded_by_user_id'], ['id'])
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id /
    # fk_users_clinic_id (both use_alter=True FKs) and dropping
    # ix_objectives_title_trgm / ix_sessions_patient_id_occurred_at — this is
    # pre-existing drift unrelated to this migration (see backend/README.md),
    # stripped here as in every prior migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_media_uploaded_by_user_id', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'media_uploaded_by_user_id')
    op.drop_column('sessions', 'media_duration_seconds')
    op.drop_column('sessions', 'media_type')
    op.drop_column('sessions', 'media_key')
    postgresql.ENUM('PHOTO', 'VIDEO', name='sessionmediatype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_session_reinforcers_session_id'), table_name='session_reinforcers')
    op.drop_index(op.f('ix_session_reinforcers_reinforcer_id'), table_name='session_reinforcers')
    op.drop_index(op.f('ix_session_reinforcers_id'), table_name='session_reinforcers')
    op.drop_table('session_reinforcers')
    op.drop_index(op.f('ix_behavior_events_session_id'), table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_patient_id'), table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_individual_owner_id'), table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_id'), table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_clinic_id'), table_name='behavior_events')
    op.drop_table('behavior_events')
    # NOTE: drop_table does NOT drop the enum type it implicitly created via
    # create_table (asymmetric with create, which does auto-create it) — drop
    # it explicitly, same reasoning as sessionmediatype above.
    postgresql.ENUM('BAIXA', 'MEDIA', 'ALTA', name='behaviorintensity').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_reinforcers_patient_id'), table_name='reinforcers')
    op.drop_index(op.f('ix_reinforcers_individual_owner_id'), table_name='reinforcers')
    op.drop_index(op.f('ix_reinforcers_id'), table_name='reinforcers')
    op.drop_index(op.f('ix_reinforcers_clinic_id'), table_name='reinforcers')
    op.drop_table('reinforcers')
    # ### end Alembic commands ###
