"""fase 4a alertas clinicos inteligentes

Revision ID: 91447c3ba292
Revises: f392ac0ade8e
Create Date: 2026-07-18 20:17:56.028774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91447c3ba292'
down_revision: Union[str, None] = 'f392ac0ade8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_alerts',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('NO_COLLECTION', 'REGRESSION', 'STAGNATION', 'FADING_CANDIDATE', name='clinicalalerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_alerts_alert_type'), 'clinical_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_clinic_id'), 'clinical_alerts', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_id'), 'clinical_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_individual_owner_id'), 'clinical_alerts', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_objective_id'), 'clinical_alerts', ['objective_id'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_patient_id'), 'clinical_alerts', ['patient_id'], unique=False)
    op.create_index('uq_clinical_alerts_active_objective_type', 'clinical_alerts', ['objective_id', 'alert_type'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    op.add_column('clinic_permission_settings', sa.Column('no_collection_days', sa.Integer(), nullable=False, server_default='14'))
    op.add_column('clinic_permission_settings', sa.Column('regression_window_sessions', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('clinic_permission_settings', sa.Column('regression_drop_pp', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('clinic_permission_settings', sa.Column('stagnation_session_count', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('clinic_permission_settings', sa.Column('stagnation_band_pp', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('clinic_permission_settings', sa.Column('fading_session_count', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('clinic_permission_settings', sa.Column('fading_independence_pct', sa.Integer(), nullable=False, server_default='80'))
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping the
    # manually-added ix_objectives_title_trgm/ix_sessions_patient_id_occurred_at indexes (not
    # represented in the ORM model). All were removed from this migration on review.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_permission_settings', 'fading_independence_pct')
    op.drop_column('clinic_permission_settings', 'fading_session_count')
    op.drop_column('clinic_permission_settings', 'stagnation_band_pp')
    op.drop_column('clinic_permission_settings', 'stagnation_session_count')
    op.drop_column('clinic_permission_settings', 'regression_drop_pp')
    op.drop_column('clinic_permission_settings', 'regression_window_sessions')
    op.drop_column('clinic_permission_settings', 'no_collection_days')
    op.drop_index('uq_clinical_alerts_active_objective_type', table_name='clinical_alerts', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index(op.f('ix_clinical_alerts_patient_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_objective_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_individual_owner_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_clinic_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_alert_type'), table_name='clinical_alerts')
    op.drop_table('clinical_alerts')
    # ### end Alembic commands ###
