"""fase5_bloco1_family_portal

Revision ID: 988fb711e782
Revises: 219b00575db0
Create Date: 2026-07-19 14:13:53.179544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988fb711e782'
down_revision: Union[str, None] = '219b00575db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Seção 29.6 — novo tipo de conta (Family Portal); o tipo enum nativo do
    # Postgres precisa do valor adicionado explicitamente (Alembic autogenerate
    # não detecta isso para enums já existentes).
    op.execute("ALTER TYPE usertype ADD VALUE IF NOT EXISTS 'FAMILY'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_accesses',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('can_view_evolution_charts', sa.Boolean(), nullable=False),
    sa.Column('can_view_upcoming_appointments', sa.Boolean(), nullable=False),
    sa.Column('can_view_team_guidance', sa.Boolean(), nullable=False),
    sa.Column('can_view_home_materials', sa.Boolean(), nullable=False),
    sa.Column('can_use_messaging', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'family_user_id', name='uq_family_accesses_patient_family_user')
    )
    op.create_index(op.f('ix_family_accesses_family_user_id'), 'family_accesses', ['family_user_id'], unique=False)
    op.create_index(op.f('ix_family_accesses_id'), 'family_accesses', ['id'], unique=False)
    op.create_index(op.f('ix_family_accesses_patient_id'), 'family_accesses', ['patient_id'], unique=False)
    op.create_table('family_messages',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_messages_id'), 'family_messages', ['id'], unique=False)
    op.create_index(op.f('ix_family_messages_patient_id'), 'family_messages', ['patient_id'], unique=False)
    op.add_column('invitations', sa.Column('patient_id', sa.Uuid(), nullable=True))
    op.alter_column('invitations', 'clinic_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_invitations_patient_id'), 'invitations', ['patient_id'], unique=False)
    op.create_foreign_key('fk_invitations_patient_id', 'invitations', 'patients', ['patient_id'], ['id'])
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'token_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Nota: Postgres não suporta remover um valor de enum (sem DROP VALUE);
    # 'FAMILY' permanece no tipo usertype mesmo após o downgrade das tabelas.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_constraint('fk_invitations_patient_id', 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_patient_id'), table_name='invitations')
    op.alter_column('invitations', 'clinic_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invitations', 'patient_id')
    op.drop_index(op.f('ix_family_messages_patient_id'), table_name='family_messages')
    op.drop_index(op.f('ix_family_messages_id'), table_name='family_messages')
    op.drop_table('family_messages')
    op.drop_index(op.f('ix_family_accesses_patient_id'), table_name='family_accesses')
    op.drop_index(op.f('ix_family_accesses_id'), table_name='family_accesses')
    op.drop_index(op.f('ix_family_accesses_family_user_id'), table_name='family_accesses')
    op.drop_table('family_accesses')
    # ### end Alembic commands ###
