"""fase 3 autenticacao de dois fatores

Revision ID: bf308ac09780
Revises: d9f8432f3974
Create Date: 2026-07-18 14:38:16.405176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf308ac09780'
down_revision: Union[str, None] = 'd9f8432f3974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping the
    # manually-added ix_objectives_title_trgm/ix_sessions_patient_id_occurred_at indexes (not
    # represented in the ORM model). All were removed from this migration on review.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
