"""fase7_modulo34_rooms_display_order

Revision ID: d017d601173a
Revises: f62d289eb6b5
Create Date: 2026-07-22 09:21:24.985253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd017d601173a'
down_revision: Union[str, None] = 'f62d289eb6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(clinic_id IS NOT NULL AND individual_owner_id IS NULL) OR (clinic_id IS NULL AND individual_owner_id IS NOT NULL)', name='ck_rooms_single_tenant_owner'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_clinic_id'), 'rooms', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_individual_owner_id'), 'rooms', ['individual_owner_id'], unique=False)
    op.add_column('appointments', sa.Column('room_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_appointments_room_id'), 'appointments', ['room_id'], unique=False)
    op.create_foreign_key('fk_appointments_room_id', 'appointments', 'rooms', ['room_id'], ['id'])
    # display_order backfills existing objectives to 0 via server_default, then
    # drops the server_default (the model only sets a Python-side default).
    op.add_column('objectives', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('objectives', 'display_order', server_default=None)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id /
    # fk_users_clinic_id (both use_alter=True FKs) and dropping
    # ix_objectives_title_trgm / ix_sessions_patient_id_occurred_at — this is
    # pre-existing drift unrelated to this migration (see backend/README.md),
    # stripped here as in every prior migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objectives', 'display_order')
    op.drop_constraint('fk_appointments_room_id', 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_room_id'), table_name='appointments')
    op.drop_column('appointments', 'room_id')
    op.drop_index(op.f('ix_rooms_individual_owner_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_clinic_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
