"""fase_4b_sugestoes_clinicas

Revision ID: db75042ca89c
Revises: 91447c3ba292
Create Date: 2026-07-19 00:44:56.633170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db75042ca89c'
down_revision: Union[str, None] = '91447c3ba292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_suggestions',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=True),
    sa.Column('training_id', sa.Uuid(), nullable=True),
    sa.Column('suggestion_type', sa.Enum('NEW_PROGRAM', 'FADING', 'MASTERY_READY', name='suggestiontype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISMISSED', name='suggestionstatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_suggestions_clinic_id'), 'clinical_suggestions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_id'), 'clinical_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_individual_owner_id'), 'clinical_suggestions', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_objective_id'), 'clinical_suggestions', ['objective_id'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_patient_id'), 'clinical_suggestions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_status'), 'clinical_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_suggestion_type'), 'clinical_suggestions', ['suggestion_type'], unique=False)
    op.create_index(op.f('ix_clinical_suggestions_training_id'), 'clinical_suggestions', ['training_id'], unique=False)
    op.create_index('uq_clinical_suggestions_objective_type', 'clinical_suggestions', ['objective_id', 'suggestion_type'], unique=True, postgresql_where=sa.text('objective_id IS NOT NULL'))
    op.create_index('uq_clinical_suggestions_patient_training_type', 'clinical_suggestions', ['patient_id', 'training_id', 'suggestion_type'], unique=True, postgresql_where=sa.text('training_id IS NOT NULL'))
    op.add_column('clinic_permission_settings', sa.Column('mastery_suggestion_session_count', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('clinic_permission_settings', sa.Column('mastery_suggestion_accuracy_pct', sa.Integer(), nullable=False, server_default='80'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_permission_settings', 'mastery_suggestion_accuracy_pct')
    op.drop_column('clinic_permission_settings', 'mastery_suggestion_session_count')
    op.drop_index('uq_clinical_suggestions_patient_training_type', table_name='clinical_suggestions', postgresql_where=sa.text('training_id IS NOT NULL'))
    op.drop_index('uq_clinical_suggestions_objective_type', table_name='clinical_suggestions', postgresql_where=sa.text('objective_id IS NOT NULL'))
    op.drop_index(op.f('ix_clinical_suggestions_training_id'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_suggestion_type'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_status'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_patient_id'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_objective_id'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_individual_owner_id'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_id'), table_name='clinical_suggestions')
    op.drop_index(op.f('ix_clinical_suggestions_clinic_id'), table_name='clinical_suggestions')
    op.drop_table('clinical_suggestions')
    # ### end Alembic commands ###
