"""fase7_modulo35_family_routine_logs_audio_messages

Revision ID: e44599f16618
Revises: d017d601173a
Create Date: 2026-07-22 11:56:42.264259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44599f16618'
down_revision: Union[str, None] = 'd017d601173a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_audio_messages',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('transcription_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_audio_messages_id'), 'family_audio_messages', ['id'], unique=False)
    op.create_index(op.f('ix_family_audio_messages_patient_id'), 'family_audio_messages', ['patient_id'], unique=False)
    op.create_table('family_routine_logs',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_routine_logs_id'), 'family_routine_logs', ['id'], unique=False)
    op.create_index(op.f('ix_family_routine_logs_patient_id'), 'family_routine_logs', ['patient_id'], unique=False)
    # can_submit_routine_logs backfills existing rows to false via server_default,
    # then drops the server_default (the model only sets a Python-side default).
    op.add_column(
        'family_accesses', sa.Column('can_submit_routine_logs', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('family_accesses', 'can_submit_routine_logs', server_default=None)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id /
    # fk_users_clinic_id (both use_alter=True FKs) and dropping
    # ix_objectives_title_trgm / ix_sessions_patient_id_occurred_at — this is
    # pre-existing drift unrelated to this migration (see backend/README.md),
    # stripped here as in every prior migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_accesses', 'can_submit_routine_logs')
    op.drop_index(op.f('ix_family_routine_logs_patient_id'), table_name='family_routine_logs')
    op.drop_index(op.f('ix_family_routine_logs_id'), table_name='family_routine_logs')
    op.drop_table('family_routine_logs')
    op.drop_index(op.f('ix_family_audio_messages_patient_id'), table_name='family_audio_messages')
    op.drop_index(op.f('ix_family_audio_messages_id'), table_name='family_audio_messages')
    op.drop_table('family_audio_messages')
    # ### end Alembic commands ###
