"""fase_4b_bloco2_avaliacoes_padronizadas

Revision ID: e4bd625e5e7d
Revises: db75042ca89c
Create Date: 2026-07-19 08:13:42.684057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bd625e5e7d'
down_revision: Union[str, None] = 'db75042ca89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('professional_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.Enum('VB_MAPP', 'ABLLS_R', name='assessmentprotocol'), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('raw_scores', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'protocol', 'applied_date', name='uq_assessments_patient_protocol_date')
    )
    op.create_index(op.f('ix_assessments_clinic_id'), 'assessments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_individual_owner_id'), 'assessments', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_assessments_patient_id'), 'assessments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_assessments_protocol'), 'assessments', ['protocol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_protocol'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_patient_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_individual_owner_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_clinic_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
