"""phase 2 treatment plans, resources, report summaries

Revision ID: e52a0826e753
Revises: 94f27f468fdb
Create Date: 2026-07-18 10:20:05.949138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a0826e753'
down_revision: Union[str, None] = '94f27f468fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Seção 13.2 — similaridade por trigramas para detecção de objetivos duplicados.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('suggested_age_range', sa.String(length=60), nullable=True),
    sa.Column('resource_type', sa.Enum('PDF', 'IMAGE', 'TEXT', name='resourcetype'), nullable=False),
    sa.Column('file_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'CLINIC_SHARED', name='resourcevisibility'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_clinic_id'), 'resources', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_individual_owner_id'), 'resources', ['individual_owner_id'], unique=False)
    op.create_table('report_summaries',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DISCARDED', name='reportsummarystatus'), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_summaries_id'), 'report_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_report_summaries_patient_id'), 'report_summaries', ['patient_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_treatment_plans_patient_id')
    )
    op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_table('objectives',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('area', sa.Enum('PSICOLOGIA', 'ABA', 'FONOAUDIOLOGIA', 'TERAPIA_OCUPACIONAL', 'PSICOPEDAGOGIA', 'FISIOTERAPIA', 'NUTRICAO', 'OUTRA', name='treatmentarea'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('strategies', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'MASTERED', 'PAUSED', 'DISCONTINUED', name='objectivestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='objectivepriority'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_id'), 'objectives', ['id'], unique=False)
    op.create_index(op.f('ix_objectives_plan_id'), 'objectives', ['plan_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_objectives_title_trgm ON objectives USING gin (title gin_trgm_ops)"
    )
    op.create_table('objective_comments',
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_comments_id'), 'objective_comments', ['id'], unique=False)
    op.create_index(op.f('ix_objective_comments_objective_id'), 'objective_comments', ['objective_id'], unique=False)
    op.create_table('objective_trainings',
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id', 'training_id', name='uq_objective_trainings')
    )
    op.create_index(op.f('ix_objective_trainings_id'), 'objective_trainings', ['id'], unique=False)
    op.create_index(op.f('ix_objective_trainings_objective_id'), 'objective_trainings', ['objective_id'], unique=False)
    op.create_index(op.f('ix_objective_trainings_training_id'), 'objective_trainings', ['training_id'], unique=False)
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping
    # ix_sessions_patient_id_occurred_at (a manually-added index not represented in the ORM
    # model). Both were removed from this migration on review — see backend/README.md.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objective_trainings_training_id'), table_name='objective_trainings')
    op.drop_index(op.f('ix_objective_trainings_objective_id'), table_name='objective_trainings')
    op.drop_index(op.f('ix_objective_trainings_id'), table_name='objective_trainings')
    op.drop_table('objective_trainings')
    op.drop_index(op.f('ix_objective_comments_objective_id'), table_name='objective_comments')
    op.drop_index(op.f('ix_objective_comments_id'), table_name='objective_comments')
    op.drop_table('objective_comments')
    op.execute("DROP INDEX IF EXISTS ix_objectives_title_trgm")
    op.drop_index(op.f('ix_objectives_plan_id'), table_name='objectives')
    op.drop_index(op.f('ix_objectives_id'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_report_summaries_patient_id'), table_name='report_summaries')
    op.drop_index(op.f('ix_report_summaries_id'), table_name='report_summaries')
    op.drop_table('report_summaries')
    op.drop_index(op.f('ix_resources_individual_owner_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_clinic_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
