"""fase5_bloco3_faturamento_por_sessao

Revision ID: f0e9d269e843
Revises: 3cfd4510cd4e
Create Date: 2026-07-19 21:27:18.625309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e9d269e843'
down_revision: Union[str, None] = '3cfd4510cd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_charges',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(clinic_id IS NOT NULL AND individual_owner_id IS NULL) OR (clinic_id IS NULL AND individual_owner_id IS NOT NULL)', name='ck_session_charges_single_tenant_owner'),
    sa.CheckConstraint('amount > 0', name='ck_session_charges_amount_positive'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_charges_clinic_id'), 'session_charges', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_session_charges_id'), 'session_charges', ['id'], unique=False)
    op.create_index(op.f('ix_session_charges_individual_owner_id'), 'session_charges', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_session_charges_patient_id'), 'session_charges', ['patient_id'], unique=False)
    op.create_index(op.f('ix_session_charges_session_id'), 'session_charges', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_charges_session_id'), table_name='session_charges')
    op.drop_index(op.f('ix_session_charges_patient_id'), table_name='session_charges')
    op.drop_index(op.f('ix_session_charges_individual_owner_id'), table_name='session_charges')
    op.drop_index(op.f('ix_session_charges_id'), table_name='session_charges')
    op.drop_index(op.f('ix_session_charges_clinic_id'), table_name='session_charges')
    op.drop_table('session_charges')
    # ### end Alembic commands ###
