"""fase 3 stripe billing

Revision ID: f392ac0ade8e
Revises: bf308ac09780
Create Date: 2026-07-18 19:50:14.300471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f392ac0ade8e'
down_revision: Union[str, None] = 'bf308ac09780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subscription_status_enum = postgresql.ENUM(
    'NONE', 'ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'UNPAID',
    name='subscriptionstatus',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('stripe_webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id', name='uq_stripe_webhook_events_event_id')
    )
    op.create_index(op.f('ix_stripe_webhook_events_id'), 'stripe_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_stripe_event_id'), 'stripe_webhook_events', ['stripe_event_id'], unique=False)
    op.add_column(
        'clinics',
        sa.Column(
            'subscription_status',
            subscription_status_enum,
            nullable=False,
            server_default='NONE',
        ),
    )
    op.add_column('clinics', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_clinics_stripe_customer_id'), 'clinics', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_clinics_stripe_subscription_id'), 'clinics', ['stripe_subscription_id'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'subscription_status',
            subscription_status_enum,
            nullable=False,
            server_default='NONE',
        ),
    )
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=False)
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping the
    # manually-added ix_objectives_title_trgm/ix_sessions_patient_id_occurred_at indexes (not
    # represented in the ORM model). All were removed from this migration on review.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'subscription_current_period_end')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    op.drop_index(op.f('ix_clinics_stripe_subscription_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_stripe_customer_id'), table_name='clinics')
    op.drop_column('clinics', 'subscription_current_period_end')
    op.drop_column('clinics', 'stripe_subscription_id')
    op.drop_column('clinics', 'stripe_customer_id')
    op.drop_column('clinics', 'subscription_status')
    op.drop_index(op.f('ix_stripe_webhook_events_stripe_event_id'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_id'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    subscription_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
