"""fase7_modulo33_objective_maintenance_generalization_appliers

Revision ID: f62d289eb6b5
Revises: 5b51e9e11096
Create Date: 2026-07-22 02:22:34.253206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f62d289eb6b5'
down_revision: Union[str, None] = '5b51e9e11096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective_appliers',
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('applier_type', sa.Enum('PROFESSIONAL', 'PARENT', name='appliertype'), nullable=False),
    sa.Column('applier_user_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['applier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id', 'applier_user_id', name='uq_objective_appliers_objective_user')
    )
    op.create_index(op.f('ix_objective_appliers_applier_user_id'), 'objective_appliers', ['applier_user_id'], unique=False)
    op.create_index(op.f('ix_objective_appliers_id'), 'objective_appliers', ['id'], unique=False)
    op.create_index(op.f('ix_objective_appliers_objective_id'), 'objective_appliers', ['objective_id'], unique=False)
    op.add_column('objectives', sa.Column('maintenance_check_date', sa.Date(), nullable=True))
    op.add_column('objectives', sa.Column('generalization_contexts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id /
    # fk_users_clinic_id (both use_alter=True FKs) and dropping
    # ix_objectives_title_trgm / ix_sessions_patient_id_occurred_at — this is
    # pre-existing drift unrelated to this migration (see backend/README.md),
    # stripped here as in every prior migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objectives', 'generalization_contexts')
    op.drop_column('objectives', 'maintenance_check_date')
    op.drop_index(op.f('ix_objective_appliers_objective_id'), table_name='objective_appliers')
    op.drop_index(op.f('ix_objective_appliers_id'), table_name='objective_appliers')
    op.drop_index(op.f('ix_objective_appliers_applier_user_id'), table_name='objective_appliers')
    op.drop_table('objective_appliers')
    # ### end Alembic commands ###
    # NOTE (Fase 6 bloco 7 / Fase 7 módulo 3.1 postmortem): drop_table não
    # derruba sozinho o enum que create_table criou implicitamente.
    postgresql.ENUM('PROFESSIONAL', 'PARENT', name='appliertype').drop(op.get_bind(), checkfirst=True)
