"""phase 2 closeout: notifications, session templates

Revision ID: fb41781cb679
Revises: e52a0826e753
Create Date: 2026-07-18 11:13:46.917127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb41781cb679'
down_revision: Union[str, None] = 'e52a0826e753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('session_templates',
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('individual_owner_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_templates_clinic_id'), 'session_templates', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_session_templates_id'), 'session_templates', ['id'], unique=False)
    op.create_index(op.f('ix_session_templates_individual_owner_id'), 'session_templates', ['individual_owner_id'], unique=False)
    op.create_index(op.f('ix_session_templates_patient_id'), 'session_templates', ['patient_id'], unique=False)
    op.create_table('session_template_trainings',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['session_templates.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_template_trainings_id'), 'session_template_trainings', ['id'], unique=False)
    op.create_index(op.f('ix_session_template_trainings_template_id'), 'session_template_trainings', ['template_id'], unique=False)
    op.create_index(op.f('ix_session_template_trainings_training_id'), 'session_template_trainings', ['training_id'], unique=False)
    # NOTE: autogenerate also proposed re-creating fk_clinics_owner_user_id/fk_users_clinic_id
    # (already present, false positive from the circular use_alter FKs) and dropping the
    # manually-added ix_objectives_title_trgm/ix_sessions_patient_id_occurred_at indexes (not
    # represented in the ORM model). All were removed from this migration on review.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_template_trainings_training_id'), table_name='session_template_trainings')
    op.drop_index(op.f('ix_session_template_trainings_template_id'), table_name='session_template_trainings')
    op.drop_index(op.f('ix_session_template_trainings_id'), table_name='session_template_trainings')
    op.drop_table('session_template_trainings')
    op.drop_index(op.f('ix_session_templates_patient_id'), table_name='session_templates')
    op.drop_index(op.f('ix_session_templates_individual_owner_id'), table_name='session_templates')
    op.drop_index(op.f('ix_session_templates_id'), table_name='session_templates')
    op.drop_index(op.f('ix_session_templates_clinic_id'), table_name='session_templates')
    op.drop_table('session_templates')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
